### ISSUE TITLE
error TS18002 when tsconfig.json is not found

### ISSUE THREAD

**Issue by vivekkpai** [TypeStrong/ts-loader#434]
In my build scenario, all compilerOptions are passed within the Webpack configuration. There are no tsconfig.json files anywhere in the source tree. Webpack configuration files are generatedon-the-fly based on information in a project repository (a database).

While this used to work with ts-loader@1.2.2 and typescript@2.0.3, it no longer does with typescript@2.1.4. Now ts-loader terminates with error:

error TS18002: The 'files' list in config file 'tsconfig.json' is empty

I tried the following combinations:

ts-loader@1.3.3 and typescript@2.1.4 // <- Fails!
ts-loader@1.2.2 and typescript@2.1.4 // <- Fails!
ts-loader@1.2.2 and typescript@2.0.3 // <- Works!!

The error seems to arise from an empty configuration that is created (in config.js line 46). For some reason, this results in an error with compiler.parseJsonConfigFileContent (config.js line 99). I didn't investigate further into the typescript compiler to see why this is the case. I also don't see changes with respect to 1.2.2 which might cause this.

A small change seems to fix this:
        //config.ts line 46
        configFile = {
            config: {
                compilerOptions: {},
                // files: [],                                 // As it exists in the repo as of 1.3.3
                files: [ loader.resourcePath ]  // Line changed to add current resource path 
            },
        };

A bug or by-design?

**Comment by johnnyreilly** [comment]
This was a change in TypeScript 2.1 - nothing to do with ts-loader I'm afraid. See https://github.com/Microsoft/TypeScript/issues/11834 for details

**Comment by elsassph** [comment]
Sorry but concretely, is there a workaround besides going back TS 2.0?
