### PR TITLE
Resolve type error #1337

### LINKED ISSUE #1337: Type error in v8: "Property 'getPackageJsonInfoCache' is optional in type 'ModuleResolutionCache' but required in type 'ModuleResolutionCache'."
### Expected Behaviour

It seems `ts-loader@8` doesn't work with TS 4.3.

Given…

`package.json`:
```json
{
  "dependencies": {
    "@types/webpack": "4.41.29",
    "ts-loader": "8.3.0",
    "typescript": "4.3.2"
  }
}
```

and

`index.ts`:
```ts
import * as tsLoader from 'ts-loader'
tsLoader;
```

When I run `tsc index.ts` I should get no errors.

### Actual Behaviour

I get this error:

```
node_modules/ts-loader/dist/interfaces.d.ts:146:18 - error TS2430: Interface 'import("/Users/oliverash/Development/ts-loader-ts-types-bug/node_modules/ts-loader/dist/interfaces").ModuleResolutionCache' incorrectly extends interface 'import("/Users/oliverash/Development/ts-loader-ts-types-bug/node_modules/typescript/lib/typescript").ModuleResolutionCache'.
  Property 'getPackageJsonInfoCache' is optional in type 'ModuleResolutionCache' but required in type 'ModuleResolutionCache'.

146 export interface ModuleResolutionCache extends typescript.ModuleResolutionCache {
                     ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### Steps to Reproduce the Problem

See above.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/OliverJAsh/ts-loader-ts-types-bug

---

To workaround this I used the following patch:

```patch
diff --git a/node_modules/ts-loader/dist/interfaces.d.ts b/node_modules/ts-loader/dist/interfaces.d.ts
index cfba2c3..ce4cea2 100644
--- a/node_modules/ts-loader/dist/interfaces.d.ts
+++ b/node_modules/ts-loader/dist/interfaces.d.ts
@@ -148,7 +148,8 @@ export interface ModuleResolutionCache extends typescript.ModuleResolutionCache
     moduleNameToDirectoryMap: CacheWithRedirects<PerModuleNameCache>;
     clear(): void;
     update(compilerOptions: typescript.CompilerOptions): void;
-    getPackageJsonInfoCache?(): any;
+    getPackageJsonInfoCache(): typescript.PackageJsonInfoCache;
 }
 export interface TypeReferenceDirectiveResolutionCache {
     getOrCreateCacheForDirectory(directoryName: string, redirectedReference?: typescript.ResolvedProjectReference): Map<string, typescript.ResolvedTypeReferenceDirectiveWithFailedLookupLocations>;
```

FYI this error does not happen with `ts-loader@9` and `@types/webpack@5`.

### PR DESCRIPTION
**Pull request by metanas**
This is my attempt to fix #1337 in webpack4 with the new typescript versions

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Got some failing builds I'm afraid
