### ISSUE TITLE
Getting 'error TS2688:' after upgrading to 0.9.5 from 0.9.1

### ISSUE THREAD

**Issue by ksharifbd** [TypeStrong/ts-loader#350]
After upgrading to `0.9.5` from `0.9.1` I get following error:

```
ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'karma-jasmine'.

ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'karma-phantomjs-launcher'.

ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'karma-remap-coverage'.

ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'karma-sourcemap-loader'.

ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'karma-webpack'.

ERROR in /Users/Admin/Downloads/kamal/development/self/provat/tsconfig.json
error TS2688: Cannot find type definition file for 'lodash'.

........
........
```
Following is my `tsconfig.json`

```
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors":true,
    "noEmitHelpers": false,
    "typeRoots": [
      "node_modules"
    ]
  }
}
```

**Comment by johnnyreilly** [comment]
I don't think you need to specify `typeRoots`. For what it's worth you can see a setup that uses Jasmine with @types here: https://github.com/johnnyreilly/proverb-signalr-react
