### PR TITLE
fix: Removed usage of loader-utils

### PR DESCRIPTION
**Pull request by JonWallsten**
Remove usage of loader-utils:
https://github.com/TypeStrong/ts-loader/pull/1286#issuecomment-823264246

### CODE REVIEW

**Comment by JonWallsten** [comment]
@alexander-akait: Is this how you meant?

Schema doesn't seem to be optional though:
image

File: yarn.lock [hunk 1]
```diff
@@ -1829,14 +1829,9 @@ emoji-regex@^8.0.0:
...
 
-emojis-list@^2.0.0:
-  version "2.1.0"
-  resolved "https://registry.npmjs.org/emojis-list/-/emojis-list-2.1.0.tgz#4daa4d9db00f9819880c79fa457ae5b09a1fd389"
-  integrity sha1-TapNnbAPmBmIDHn6RXrlsJof04k=
-
 emojis-list@^3.0.0:
   version "3.0.0"
-  resolved "https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz#5570662046ad29e2e916e71aae260abdff4f6a78"
+  resolved "https://registry.yarnpkg.com/emojis-list/-/emojis-list-3.0.0.tgz#5570662046ad29e2e916e71aae260abdff4f6a78"
```
[the remark this answers is not in the document]
Comment (JonWallsten) [reply yarn.lock:1834]: loader-utils@^1.0.2 is used by babel-loader I think. Probably has something to do with the tests.

[the remark this answers is not in the document]
Comment (alexander-akait) [reply yarn.lock:1834]: `babel-loader` support old versions of webpack, they drop it in future, ideally we should improve `getOptions` on webpack side like: `getOptions<T extends object>(schema: any): T;`

**Comment by JonWallsten** [comment]
@alexander-akait:
image

I guess that has something to do with this?
image

File: src/index.ts [hunk 2]
```diff
@@ -646,7 +643,7 @@ function makeSourceMap(
   return {
     output: outputText.replace(/^\/\/# sourceMappingURL=[^\r\n]*/gm, ''),
     sourceMap: Object.assign(JSON.parse(sourceMapText), {
-      sources: [loaderUtils.getRemainingRequest(loaderContext)],
+      sources: loaderContext.remainingRequest,
```
[the remark this answers is not in the document]
Comment (JonWallsten) [reply src/index.ts:646]: Of course! Now I feel stupid! 😅

File: yarn.lock (hunk 1 above)
[the remark this answers is not in the document]
Comment (johnnyreilly) [reply yarn.lock:1834]: It's definitely optional: https://github.com/webpack/webpack/blob/85fe6ac4f436384e2a20c7996c70f14e4172ccd8/lib/NormalModule.js#L495

It's our definition in this case that's causing the issue.  But I'm fine with that.  I'm hoping this will resolve it in future: https://github.com/webpack/webpack/pull/13164

**Review by johnnyreilly — APPROVED** [review]

**Review by alexander-akait — COMMENTED** [review]
Great

**Comment by johnnyreilly** [comment]
Shipping with https://github.com/TypeStrong/ts-loader/releases/tag/v9.0.2

File: yarn.lock (hunk 1 above)
[the remark this answers is not in the document]
Comment (JonWallsten) [reply yarn.lock:1834]: @alexander-akait: If I'm not mistaken you need `getOptions<T extends object>(schema?: any): T;` to make it truly optional in strict mode. That's why I had to send in `undefined`. I can be wrong here though.

**Comment by johnnyreilly** [comment]
Hi,

Thanks for reporting. Can you confirm that `9.0.1` works without issue please?

**Comment by jamestalton** [comment]
Verified that ts-loader 9.0.1 works and 9.0.2 does not for our storybook.
We could always have something not setup right, but it has been working.
https://github.com/open-cluster-management/ui-components

**Comment by alexander-akait** [comment]
@jamestalton most likely you have two webpacks, run `npm ls webpack`/`yarn why webpack`

**Comment by JonWallsten** [comment]
@jamestalton: ts-loader 9.x.x is for Webpack >= 5. That's probably why you get the issue!

**Comment by gligoran** [comment]
I'm getting the following error with ts-loader 9.0.2 or later:

```
👀  ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/Users/gligoran/dev/my-project/node_modules/ts-loader/dist/index.js:90:41)
    at Object.loader (/Users/gligoran/dev/my-project/node_modules/ts-loader/dist/index.js:14:21)
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
```

The suggestion at the end does nothing.

The same app does work with ts-loader 9.0.1.

**Comment by sandro768** [comment]
> I'm getting the following error with ts-loader 9.0.2 or later:
> 
> ```
> 👀  ./src/index.ts
> Module build failed (from ./node_modules/ts-loader/index.js):
> TypeError: loaderContext.getOptions is not a function
>     at getLoaderOptions (/Users/gligoran/dev/my-project/node_modules/ts-loader/dist/index.js:90:41)
>     at Object.loader (/Users/gligoran/dev/my-project/node_modules/ts-loader/dist/index.js:14:21)
> Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
> ```
> 
> The suggestion at the end does nothing.
> 
> The same app does work with ts-loader 9.0.1.

I've got the same issue

**Comment by JonWallsten** [comment]
@gligoran, @sandro768: You most probably have webpack@4.x.x in you project.

**Comment by gligoran** [comment]
> @gligoran, @sandro768: You most probably have [webpack@4.x.x](mailto:webpack@4.x.x) in you project.

Oh, sorry. I've seen that comment about this a bit up and wanted to mention it in mine, but forgot.

I was using webpack 4 and upgraded to 5. Here are my relevant devDeps:

```
+-- ts-loader@9.0.1
+-- typescript@4.2.4
+-- webpack@5.36.0
`-- webpack-cli@4.6.0
```

If I upgrade to `tsloader@9.0.2` or above it produces the error in my previous comment.

Here's my `webpack.config.js`:

```js
const path = require('path');

const mode = process.env.NODE_ENV || 'production';

module.exports = {
  mode,
  entry: './src/index.ts',
  target: 'webworker',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
        },
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  output: {
    filename: `worker.js`,
    path: path.join(__dirname, 'dist'),
  },
};
```

Could this be a problem with upgrading from 4 in terms of old config style?

**Comment by alexander-akait** [comment]
@gligoran run `yarn why webpack`/`npm ls webpack`

**Comment by gligoran** [comment]
> @gligoran run `yarn why webpack`/`npm ls webpack`

Here's what that returns (just updated to the newest version of webpack):

```
 $ npm ls --depth=10 webpack
`-- webpack@5.36.1
```

I also ran this, if there's any other webpack stuff that might lend a better insight:

```
$ npm ls --depth=10 | grep webpack
+-- webpack@5.36.1
| +-- terser-webpack-plugin@5.1.1
| `-- webpack-sources@2.2.0
`-- webpack-cli@4.6.0
  +-- @webpack-cli/configtest@1.0.2
  +-- @webpack-cli/info@1.2.3
  +-- @webpack-cli/serve@1.3.1
  `-- webpack-merge@5.7.3
```

**Comment by alexander-akait** [comment]
@gligoran What is the error?

**Comment by gligoran** [comment]
> @gligoran What is the error?

I've posted it here: https://github.com/TypeStrong/ts-loader/pull/1288#issuecomment-828441995

Or is this not detailed enough? If so, how can I provide more info?

**Comment by alexander-akait** [comment]
@gligoran do you use `thread-loader`, this error means you still on webpack v4 or something change loader context (`thread-loader`)

**Comment by gligoran** [comment]
> @gligoran do you use `thread-loader`, this error means you still on webpack v4 or something change loader context (`thread-loader`), anyway if you provide repo I can look

It seems that [wrangler](https://github.com/cloudflare/wrangler/tree/master/wranglerjs) replaces the installed webpack version. So, it seems we're still running webpack 4 regardless of what's installed in the repo itself.

**Comment by cinderblock** [comment]
I am getting this error with Webpack 5 and `ts-loader@9.2.5`. Downgrading to `9.0.1` gets me past this error.

```log
ERROR in ./main.tsx
Module build failed (from ../node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (C:\Users\camer\git\my-project\node_modules\ts-loader\dist\index.js:90:41)
    at Object.loader (C:\Users\camer\git\my-project\node_modules\ts-loader\dist\index.js:14:21)
```
