### ISSUE TITLE
Type error in v8: "Property 'getPackageJsonInfoCache' is optional in type 'ModuleResolutionCache' but required in type 'ModuleResolutionCache'."

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-loader#1337]
### Expected Behaviour

It seems `ts-loader@8` doesn't work with TS 4.3.

Given…

`package.json`:
```json
{
  "dependencies": {
    "@types/webpack": "4.41.29",
    "ts-loader": "8.3.0",
    "typescript": "4.3.2"
  }
}
```

and

`index.ts`:
```ts
import * as tsLoader from 'ts-loader'
tsLoader;
```

When I run `tsc index.ts` I should get no errors.

### Actual Behaviour

I get this error:

```
node_modules/ts-loader/dist/interfaces.d.ts:146:18 - error TS2430: Interface 'import("/Users/oliverash/Development/ts-loader-ts-types-bug/node_modules/ts-loader/dist/interfaces").ModuleResolutionCache' incorrectly extends interface 'import("/Users/oliverash/Development/ts-loader-ts-types-bug/node_modules/typescript/lib/typescript").ModuleResolutionCache'.
  Property 'getPackageJsonInfoCache' is optional in type 'ModuleResolutionCache' but required in type 'ModuleResolutionCache'.

146 export interface ModuleResolutionCache extends typescript.ModuleResolutionCache {
                     ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### Steps to Reproduce the Problem

See above.

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/OliverJAsh/ts-loader-ts-types-bug

---

To workaround this I used the following patch:

```patch
diff --git a/node_modules/ts-loader/dist/interfaces.d.ts b/node_modules/ts-loader/dist/interfaces.d.ts
index cfba2c3..ce4cea2 100644
--- a/node_modules/ts-loader/dist/interfaces.d.ts
+++ b/node_modules/ts-loader/dist/interfaces.d.ts
@@ -148,7 +148,8 @@ export interface ModuleResolutionCache extends typescript.ModuleResolutionCache
     moduleNameToDirectoryMap: CacheWithRedirects<PerModuleNameCache>;
     clear(): void;
     update(compilerOptions: typescript.CompilerOptions): void;
-    getPackageJsonInfoCache?(): any;
+    getPackageJsonInfoCache(): typescript.PackageJsonInfoCache;
 }
 export interface TypeReferenceDirectiveResolutionCache {
     getOrCreateCacheForDirectory(directoryName: string, redirectedReference?: typescript.ResolvedProjectReference): Map<string, typescript.ResolvedTypeReferenceDirectiveWithFailedLookupLocations>;
```

FYI this error does not happen with `ts-loader@9` and `@types/webpack@5`.

**Comment by johnnyreilly** [comment]
Haha. Ouch. Yeah - this will be down to a change in TypeScripts exposed types. If you look at the change to `interfaces.ts` in this PR: https://github.com/TypeStrong/ts-loader/pull/1330/files#diff-f3fc934cf0d89bdf07de358896ff90f1202585df812cf606206d1830a9949811

You can see how we cater for it with ts-loader 9. We could probably apply the same change to ts-loader 8 given there's many folk who haven't moved to webpack 5 yet. Would be happy to receive a PR and collaborate.

Hi Oliver BTW!

**Comment by OliverJAsh** [comment]
> Hi Oliver BTW!

👋👋👋 😄 

Thanks, that makes sense. We'll use the patch for now to workaround this but I'll try to contribute a PR soon!

**Comment by johnnyreilly** [comment]
Thanks! Please remember to target the webpack 4 branch if you do. Hadn't expected for that to keep shipping, but there's clearly demand!

**Comment by johnnyreilly** [comment]
Not sure to be honest - I don't remember
